# Generated by Django 5.0.4 on 2024-05-03 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='fathers_name',
            field=models.CharField(default='Jahangir', max_length=20),
        ),
    ]
