# Generated by Django 5.0.4 on 2024-05-02 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_student_father_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='father_name',
            field=models.TextField(default='Jahangir'),
        ),
    ]
